/**
 * Interview Types
 *
 * Type definitions for the project interview wizard feature.
 */

// ============================================
// Interview Stage & State
// ============================================

/**
 * Interview stage progression.
 */
export type InterviewStage = 'seed_name' | 'seed_idea' | 'interview' | 'finalize' | 'done';

/**
 * User's technical proficiency level.
 */
export type TechLevel = 'technical' | 'non_technical' | 'mixed';

/**
 * Interview depth preset (number of questions).
 */
export type InterviewDepth = 'quick' | 'normal' | 'pro';

/**
 * How to determine user's tech level.
 */
export type TechLevelMode = 'ask' | 'infer';

// ============================================
// User Profile
// ============================================

/**
 * User profile gathered during interview.
 */
export interface InterviewUserProfile {
  level: TechLevel;
  inferredFromResponse?: boolean;
}

// ============================================
// Questions & Answers
// ============================================

/**
 * A question generated by Ralph during the interview.
 */
export interface InterviewQuestion {
  id: string;
  index: number;
  text: string;
  context?: string;
  suggestedOptions?: string[];
  exampleAnswer?: string;
  category: InterviewQuestionCategory;
  isRequired: boolean;
}

/**
 * Categories of interview questions for coverage tracking.
 */
export type InterviewQuestionCategory =
  | 'scope'
  | 'technology'
  | 'timeline'
  | 'constraints'
  | 'features'
  | 'users'
  | 'integrations'
  | 'other';

/**
 * An answer provided by the user.
 */
export interface InterviewAnswer {
  questionId: string;
  questionIndex: number;
  questionText: string;
  answer: string;
  skipped: boolean;
  timestamp: string;
}

/**
 * An assumption made when user skips a question or provides vague answer.
 */
export interface InterviewAssumption {
  id: string;
  questionId: string;
  assumption: string;
  reason: string;
  timestamp: string;
}

/**
 * A risk identified during the interview.
 */
export interface InterviewRisk {
  id: string;
  description: string;
  severity: 'low' | 'medium' | 'high';
  mitigation?: string;
}

// ============================================
// Project Brief
// ============================================

/**
 * Summary brief generated from interview answers.
 */
export interface ProjectBrief {
  name: string;
  summary: string;
  goals: string[];
  techStack: string[];
  constraints: string[];
  timeline?: string;
  targetUsers?: string;
  assumptions: InterviewAssumption[];
  risks: InterviewRisk[];
}

// ============================================
// Backlog Generation
// ============================================

/**
 * An epic for organizing stories in the backlog.
 */
export interface BacklogEpic {
  name: string;
  color: string;
  description?: string;
  stories: BacklogStory[];
}

/**
 * A story/task to be created from the backlog.
 */
export interface BacklogStory {
  title: string;
  description: string;
  acceptanceCriteria: string[];
  priority: 'low' | 'medium' | 'high' | 'critical';
  isSetupTask: boolean;
  estimatedComplexity?: 'simple' | 'medium' | 'complex';
}

// ============================================
// Main Interview State
// ============================================

/**
 * Complete interview state that gets persisted.
 */
export interface InterviewState {
  /** Current stage in the wizard */
  stage: InterviewStage;

  /** OS locale detected from Electron */
  osLanguage: string;

  /** User's detected language (after first response) */
  detectedUserLanguage: string | null;

  /** How to determine tech level */
  techLevelMode: TechLevelMode;

  /** User profile (tech level) */
  userProfile: InterviewUserProfile;

  /** Total number of questions for this interview */
  nQuestions: number;

  /** Current question index (0-based) */
  currentIndex: number;

  /** Current question being asked */
  currentQuestion: InterviewQuestion | null;

  /** Project name */
  projectName: string;

  /** Project idea description */
  projectIdea: string;

  /** All answers collected */
  answers: InterviewAnswer[];

  /** Assumptions made during interview */
  assumptions: InterviewAssumption[];

  /** Identified risks */
  risks: InterviewRisk[];

  /** Generated project brief */
  projectBrief: ProjectBrief | null;

  /** Generated backlog draft */
  backlogDraft: BacklogEpic[] | null;

  /** Path to the project being created */
  projectPath: string | null;

  /** Interview creation timestamp */
  createdAt: string;

  /** Last update timestamp */
  updatedAt: string;
}

// ============================================
// Interview Configuration
// ============================================

/**
 * Configuration options when starting an interview.
 */
export interface InterviewConfig {
  projectPath: string;
  osLanguage: string;
  depth?: InterviewDepth;
  techLevelMode?: TechLevelMode;
  /** Optional project name (used when syncing from frontend) */
  projectName?: string;
  /** Optional project idea (used when syncing from frontend) */
  projectIdea?: string;
}

/**
 * Maps depth preset to number of questions.
 */
export const INTERVIEW_DEPTH_MAP: Record<InterviewDepth, number> = {
  quick: 3,
  normal: 5,
  pro: 8,
};

// ============================================
// Interview IPC Types
// ============================================

/**
 * Stream update types for interview responses.
 */
export type InterviewStreamType = 'question' | 'options' | 'example' | 'brief' | 'backlog';

/**
 * Stream update sent from main to renderer.
 */
export interface InterviewStreamUpdate {
  type: InterviewStreamType;
  content: string;
  done: boolean;
}

/**
 * Result of submitting an answer.
 */
export interface SubmitAnswerResult {
  state: InterviewState;
  nextQuestion: InterviewQuestion | null;
  isComplete: boolean;
}

/**
 * Result of creating tasks from backlog.
 */
export interface CreateTasksResult {
  success: boolean;
  taskCount: number;
  setupTaskCount: number;
  backlogTaskCount: number;
  error?: string;
}
